export enum ModulesOptions {
  Home = 'home',
  Companies = 'companies',
  Contacts = 'contacts',
  CustomerSessions = 'customerSessions',
  Opportunities = 'opportunities',
  Offers = 'offers',
  Contracts = 'contracts',
  Shops = 'shops',
  EditProfile = 'editProfile',
  Catalogue = 'catalogue',
  Regions = 'regions',
  UserManagement = 'userManagement',
  Logout = 'logout',
}
